'use strict';
// Fictional prototype data only. No credentials, persistence, school requests or external assets.
const TERM_START = '2026-09-14', TERM_END = '2027-01-24', TODAY = '2026-10-02', NOW = 570;
const DAYS = ['周一','周二','周三','周四','周五','周六','周日'];
const COLORS = ['blue','pink','yellow','mint','purple'];
const COLOR_NAMES = ['浅蓝','浅粉','浅黄','薄荷绿','淡紫'];
const PERIODS = [[510,555],[555,600],[620,665],[665,710],[840,885],[885,930],[950,995],[995,1040],[1110,1155],[1155,1200],[1220,1265],[1265,1310]];
const ALL_WEEKS = Array.from({length:18},(_,i)=>i+1);
const seed = [
 {id:'math',name:'高等数学',teacher:'陈老师（示例）',location:'示例 A101',weekday:5,periods:[1,2],color:'blue'},
 {id:'design',name:'数字媒体与交互设计基础',teacher:'李老师（示例）',location:'示例 B203',weekday:5,periods:[3,4],color:'purple'},
 {id:'english',name:'大学英语',teacher:'周老师（示例）',location:'示例 C102',weekday:5,periods:[5,6],color:'mint'},
 {id:'history',name:'设计史',teacher:'吴老师（示例）',location:'示例 D201',weekday:5,timeMode:'custom',start:885,end:960,color:'pink'},
 {id:'data',name:'数据结构',teacher:'李老师（示例）',location:'示例 B203',weekday:1,periods:[3,4],color:'blue'},
 {id:'sport',name:'体育',teacher:'张老师（示例）',location:'',weekday:2,periods:[7,8],color:'yellow',weeks:[1,3,5,7,9,11,13,15,17]},
 {id:'english2',name:'大学英语',teacher:'周老师（示例）',location:'示例 C102',weekday:3,periods:[5,6],color:'mint'},
 {id:'algebra',name:'线性代数',teacher:'陈老师（示例）',location:'示例 A201',weekday:4,periods:[1,2],color:'pink'},
].map(c=>({weeks:[...ALL_WEEKS],timeMode:'period',...c}));
let courses = structuredClone(seed), exceptions = {}, view = 'home', selectedDate = TODAY, selectedEvent = null, originView = 'home', editContext = null, draft = null, errors = {}, dirty = false, theme = 'system', dialogAction = null, toastUndo = null, toastTimer;
const $ = s => document.querySelector(s);
const esc = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svgPaths = {plus:'M12 4v16M4 12h16',back:'m14 5-7 7 7 7M7 12h13',left:'m14 5-7 7 7 7',right:'m9 5 7 7-7 7',calendar:'M5 5h14v15H5zM8 3v4M16 3v4M5 10h14M8 14h2M14 14h2M8 17h2',home:'m3 10 9-7 9 7M5 9v11h14V9M10 20v-7h4v7',grid:'M4 4h16v16H4zM4 9h16M9 4v16M14 4v16M4 14h16',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-3a8 8 0 0 1 16 0v3Z',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 7v5l3 2',pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0M14 10a2 2 0 1 1-4 0 2 2 0 0 1 4 0',edit:'m4 16 12-12 4 4-12 12-5 1zM13 7l4 4',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M5 19l1-1M18 6l1-1',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',screen:'M3 4h18v14H3zM8 22h8M12 18v4',check:'m5 12 4 4L19 6',stop:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M6 6l12 12',book:'M4 4h16v16H4zM8 4v16M11 8h6M11 12h6',swap:'M4 7h16l-4-4M20 17H4l4 4'};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${svgPaths[name] || svgPaths.book}"/></svg>`;
const iconBtn = (name,label,action,attrs='') => `<button class="icon-btn" aria-label="${esc(label)}" data-action="${action}" ${attrs}>${icon(name)}</button>`;
const books = '<img class="pixel-books" src="assets/books.svg" alt="" aria-hidden="true">';
const toDate = s => new Date(s+'T12:00:00Z');
const addDays = (s,n) => {const d=toDate(s);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const dayIndex = s => (toDate(s).getUTCDay()+6)%7;
const weekOf = s => Math.floor((toDate(s)-toDate(TERM_START))/604800000)+1;
const monday = s => addDays(s,-dayIndex(s));
const fmtDate = s => `${toDate(s).getUTCMonth()+1}月${toDate(s).getUTCDate()}日`;
const hm = n => `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const min = s => {if(!/^\d{2}:\d{2}$/.test(s)) return NaN; const [h,m]=s.split(':').map(Number);return h<=23&&m<=59?h*60+m:NaN;};
const key = (id,date) => `${id}@${date}`;
function segments(c){
 if(c.timeMode==='custom') return [[c.start,c.end]];
 const result=[];
 for(const p of [...c.periods].sort((a,b)=>a-b)){const t=PERIODS[p-1];if(!t)continue;const prev=result.at(-1);if(prev&&prev[1]===t[0])prev[1]=t[1];else result.push([...t]);}
 return result;
}
function timeText(c){return segments(c).map(([a,b])=>`${hm(a)}–${hm(b)}`).join(' / ');}
function weekText(ws){const arr=[...new Set(ws)].sort((a,b)=>a-b),groups=[];for(let i=0;i<arr.length;i++){let a=arr[i],b=a;while(arr[i+1]===b+1)b=arr[++i];groups.push(a===b?String(a):`${a}-${b}`);}return groups.join(',');}
function eventsFor(date){
 const events=[];
 for(const c of courses){if(c.weekday!==dayIndex(date)+1||!c.weeks.includes(weekOf(date)))continue;const ex=exceptions[key(c.id,date)];if(ex?.action==='cancel')continue;if(ex?.action==='move'&&ex.targetDate!==date)continue;events.push({...c,...(ex?.changes||{}),originalDate:date,date,moved:!!ex});}
 for(const [k,ex] of Object.entries(exceptions)){if(ex.action!=='move'||ex.targetDate!==date)continue;const [id,originalDate]=k.split('@');if(originalDate===date)continue;const c=courses.find(x=>x.id===id);if(c)events.push({...c,...ex.changes,originalDate,date,moved:true});}
 events.sort((a,b)=>segments(a)[0][0]-segments(b)[0][0]);
 return events.map(e=>({...e,conflict:events.some(o=>key(o.id,o.originalDate)!==key(e.id,e.originalDate)&&segments(e).some(([a,b])=>segments(o).some(([c,d])=>a<d&&c<b)))}));
}
function eventFromSelection(){return eventsFor(selectedEvent.date).find(e=>e.id===selectedEvent.id&&e.originalDate===selectedEvent.originalDate);}
function nextEvent(date,includeToday=true){for(let i=includeToday?0:1;i<=140;i++){const d=addDays(date,i);if(d>TERM_END)break;const e=eventsFor(d).find(c=>d!==TODAY||segments(c).at(-1)[1]>NOW);if(e)return e;}return null;}
function toast(message,undo){clearTimeout(toastTimer);toastUndo=undo||null;$('#toast').innerHTML=`<span>${esc(message)}</span>${undo?'<button data-action="undo">撤销</button>':''}`;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),undo?8000:3000);}
function applyTheme(){document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):theme;}
matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{if(theme==='system')applyTheme();});
function openDialog(title,content,yes,callback){dialogAction=callback;$('#dialog').innerHTML=`<h2 id="dialog-title">${esc(title)}</h2>${content}<div class="dialog-actions"><button class="secondary-btn" data-action="dialog-cancel">取消</button><button class="primary-btn" data-action="dialog-confirm">${esc(yes)}</button></div>`;$('#dialog').showModal();}
function navigate(v){view=v;render();$('#screen').scrollTop=0;}
function goBack(){if(view==='edit'&&dirty){openDialog('放弃这次修改？','<p>尚未保存的内容将不会保留。</p>','放弃修改',()=>navigate(editContext.from));return;}navigate(view==='edit'?editContext.from:originView);}
function render(){
 const main=['home','week','profile'].includes(view);$('#screen').className=view==='week'?'week-screen':'';
 $('#tabbar').className=main?'':'hidden';$('#tabbar').innerHTML=[['home','首页','home'],['week','课表','grid'],['profile','我的','user']].map(([v,l,i])=>`<button class="tab ${view===v?'selected':''}" data-action="nav" data-view="${v}" aria-current="${view===v?'page':'false'}"><span class="tab-icon">${icon(i)}</span>${l}</button>`).join('');
 if(main){$('#topbar').innerHTML=`<div><h1 class="brand">${view==='profile'?'我的手账':'双轨'}</h1><div class="brand-caption">${view==='home'?'把今天，安排得刚刚好':view==='week'?'一周的节奏，一眼看懂':'留一点时间给自己'}</div></div><div class="top-actions">${view==='profile'?'<span class="demo-tag">演示数据</span>':iconBtn('calendar','选择日期','date')+iconBtn('plus','新增课程','new')}</div>`;}
 else{$('#topbar').innerHTML=iconBtn('back','返回','back')+`<h1 class="top-title">${view==='detail'?'课程详情':editContext.mode==='new'?'添加课程':editContext.mode==='once'?'调整这一次':'编辑课程'}</h1><span class="top-spacer"></span>`;}
 $('#screen').innerHTML=view==='home'?homeHTML():view==='week'?weekHTML():view==='profile'?profileHTML():view==='detail'?detailHTML():editHTML();
 if(view==='week'){const target=dayIndex(selectedDate);requestAnimationFrame(()=>{$('.week-scroll').scrollLeft=Math.max(0,42+target*112-70);});}
}
function homeHTML(){
 const events=eventsFor(selectedDate),wd=monday(selectedDate),next=selectedDate===TODAY?events.find(e=>segments(e)[0][0]>NOW):events[0];
 const upcoming=nextEvent(selectedDate,false);
 const title=selectedDate===TODAY?'今天':fmtDate(selectedDate);
 return `<div class="view"><div class="row spread"><div><span class="date-title">${title}</span> <span class="small muted">${DAYS[dayIndex(selectedDate)]} · 第${weekOf(selectedDate)}周</span></div><span class="demo-tag">演示数据</span></div><div class="week-strip">${DAYS.map((d,i)=>{const date=addDays(wd,i);return `<button class="day-button ${date===selectedDate?'selected':''} ${date===TODAY?'today':''}" data-action="day" data-date="${date}" aria-label="${fmtDate(date)} ${d}" aria-pressed="${date===selectedDate}"><span>${d}</span>${toDate(date).getUTCDate()}</button>`;}).join('')}</div>${next?`<button class="next-card" data-action="detail" data-id="${next.id}" data-date="${next.date}" data-original="${next.originalDate}"><div class="next-copy"><div class="next-label">${selectedDate===TODAY?'下一节课':'这一天的第一节课'} · ${hm(segments(next)[0][0])}</div><h2>${esc(next.name)}</h2><div class="next-meta">${esc(next.location||'教室待确认')}<br>${timeText(next)}</div>${selectedDate===TODAY?`<span class="next-countdown">还有 ${segments(next)[0][0]-NOW} 分钟</span>`:''}</div>${books}</button>`:''}${events.length?`<div class="row spread"><h2 class="section-title">${selectedDate===TODAY?'今日课程':'当天课程'}</h2><span class="small muted">${events.length} 门课</span></div><div class="timeline">${events.map(e=>{const ss=segments(e),finished=selectedDate===TODAY&&ss.at(-1)[1]<=NOW,active=selectedDate===TODAY&&ss.some(([a,b])=>a<=NOW&&NOW<b);return `<div class="timeline-item"><div class="timeline-time"><b>${hm(ss[0][0])}</b><span>${hm(ss.at(-1)[1])}</span></div><button class="course-card ${finished?'finished':''}" style="--course-bg:var(--${e.color})" data-action="detail" data-id="${e.id}" data-date="${e.date}" data-original="${e.originalDate}"><h3>${esc(e.name)}</h3><p>${timeText(e)} · ${esc(e.location||'教室待确认')}</p><p>${esc(e.teacher||'教师待确认')}</p>${active||finished||e.conflict||e.moved?`<div class="labels">${active?'<span class="course-label">正在上课</span>':''}${finished?'<span class="course-label">已结束</span>':''}${e.conflict?'<span class="course-label">时间冲突</span>':''}${e.moved?'<span class="course-label">单次调整</span>':''}</div>`:''}</button></div>`;}).join('')}</div>`:`<div class="empty">${books}<h2>${selectedDate===TODAY?'今日无课':'这一天没有课'}</h2><p>${upcoming?`下一次上课在 ${fmtDate(upcoming.date)} ${DAYS[dayIndex(upcoming.date)]}<br>${esc(upcoming.name)} · ${timeText(upcoming)}`:'本学期已没有后续课程'}</p>${upcoming?`<button data-action="day" data-date="${upcoming.date}">看看下一次课程 ${icon('right')}</button>`:''}</div>`}<p class="end-note">${events.length?'课表之外，也记得休息一下':'给自己留一点空白'}</p></div>`;
}
function weekHTML(){
 const start=monday(selectedDate),w=weekOf(selectedDate),flat=DAYS.map((_,i)=>eventsFor(addDays(start,i)).flatMap(e=>segments(e).map(([a,b])=>({...e,a,b}))));
 const widths=[],layouts=flat.map(events=>{events.sort((a,b)=>a.a-b.a);let group=[],end=0;const groups=[];for(const e of events){if(group.length&&e.a>=end){groups.push(group);group=[];}group.push(e);end=Math.max(e.b,group.length===1?0:end);}if(group.length)groups.push(group);let maxLanes=1;for(const g of groups){const ends=[];for(const e of g){let lane=ends.findIndex(x=>x<=e.a);if(lane<0)lane=ends.length;ends[lane]=e.b;e.lane=lane;}maxLanes=Math.max(maxLanes,ends.length);for(const e of g)e.lanes=ends.length;}widths.push(Math.max(112,maxLanes*56));return events;});
 const axisStart=Math.min(480,...flat.flat().map(e=>Math.floor(e.a/60)*60)),axisEnd=Math.max(1320,...flat.flat().map(e=>Math.ceil(e.b/60)*60));
 return `<div class="week-top view"><div class="row spread"><h2>第 ${w} 周 <span class="small muted">${toDate(start).getUTCMonth()+1}月</span></h2><div class="week-navigation">${iconBtn('left','上一周','prev-week',w<=1?'disabled':'')}${iconBtn('right','下一周','next-week',w>=19?'disabled':'')}</div></div><p class="week-help">${fmtDate(start)} — ${fmtDate(addDays(start,6))} · 左右滑动看整周</p></div><div class="week-scroll"><div class="week-grid" style="grid-template-columns:42px ${widths.map(w=>w+'px').join(' ')};grid-template-rows:62px ${axisEnd-axisStart}px"><div class="week-corner"></div>${DAYS.map((d,i)=>`<button class="week-header ${addDays(start,i)===selectedDate?'selected':''}" style="grid-column:${i+2}" data-action="day" data-date="${addDays(start,i)}" aria-label="查看 ${fmtDate(addDays(start,i))} ${d} 课程"><span>${d}</span><strong>${toDate(addDays(start,i)).getUTCDate()}</strong></button>`).join('')}<div class="week-axis">${Array.from({length:(axisEnd-axisStart)/60},(_,i)=>`<span class="hour-label" style="--y:${i*60}px">${i+axisStart/60}:00</span>`).join('')}</div>${layouts.map((es,i)=>`<div class="day-column ${addDays(start,i)===selectedDate?'selected':''}" style="grid-column:${i+2}">${es.map(e=>`<button class="week-event ${e.conflict?'conflict':''} ${e.b-e.a<80?'short':''}" style="--course-bg:var(--${e.color});top:${e.a-axisStart}px;height:${Math.max(48,e.b-e.a-3)}px;left:${3+e.lane*(widths[i]/e.lanes)}px;width:${widths[i]/e.lanes-6}px" data-action="detail" data-id="${e.id}" data-date="${e.date}" data-original="${e.originalDate}" aria-label="${esc(e.name)}，${hm(e.a)}至${hm(e.b)}，${esc(e.location||'教室待确认')}${e.conflict?'，时间冲突':''}"><strong>${esc(e.name)}</strong><span>${hm(e.a)}–${hm(e.b)}</span><span class="week-room">${esc(e.location||'地点待确认')}</span></button>`).join('')}${addDays(start,i)===TODAY?`<div class="now-line" style="top:${NOW-axisStart}px"></div>`:''}</div>`).join('')}</div></div>`;
}
function detailHTML(){const e=eventFromSelection();if(!e)return '<p class="notice">这次课程已调整，请返回课表查看。</p>';return `<div class="view"><div class="detail-hero" style="--course-bg:var(--${e.color})">${books}<div><h1>${esc(e.name)}</h1><div class="chips"><span class="chip">${e.moved?'单次调整':'常规课程'}</span><span class="chip">演示数据</span></div></div></div><div class="info-list">${[['clock','上课时间',`${fmtDate(e.date)} ${DAYS[dayIndex(e.date)]}<br>${timeText(e)}`],['pin','上课地点',esc(e.location||'教室未提供，待确认')],['user','授课教师',esc(e.teacher||'教师未提供，待确认')],['calendar','教学周次',`第 ${weekText(e.weeks)} 周`],['book','时间方式',e.timeMode==='period'?`第 ${e.periods.join('、')} 节`:'自定义时间']].map(([i,label,value])=>`<div class="info-row">${icon(i)}<div><b>${label}</b><p>${value}</p></div></div>`).join('')}</div>${e.conflict?'<p class="notice danger">本次课程与其他课程时间重叠。可以保留，请自行确认安排。</p>':''}${e.moved?`<p class="notice">本次课程已调整，原上课日期为 ${fmtDate(e.originalDate)}。其余周次继续按常规安排。</p>`:''}<div class="detail-secondary"><button class="secondary-btn" data-action="edit-once">${icon('swap')} 调整这一次</button><button class="secondary-btn danger" data-action="cancel-once">${icon('stop')} 本次停课</button></div><div class="action-area"><button class="primary-btn" data-action="edit-whole">${icon('edit')} 编辑整门课程</button></div></div>`;}
function beginEdit(mode){const e=selectedEvent&&eventFromSelection(),c=e&&courses.find(x=>x.id===e.id);editContext={mode,from:view,id:c?.id,originalDate:e?.originalDate,date:e?.date};draft=mode==='new'?{name:'',teacher:'',location:'',weekday:dayIndex(selectedDate)+1,timeMode:'period',periodText:'1,2',weekText:'1-18',weekFilter:'all',color:'blue',start:'08:30',end:'10:00',targetDate:selectedDate}:{...structuredClone(mode==='once'?e:c),periodText:(mode==='once'?e:c).periods?.join(',')||'1,2',weekText:weekText(c.weeks),weekFilter:'all',start:hm(segments(mode==='once'?e:c)[0][0]),end:hm(segments(mode==='once'?e:c).at(-1)[1]),targetDate:e.date};errors={};dirty=false;navigate('edit');}
function field(label,name,type='text',placeholder='',attrs=''){return `<div class="form-field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(draft[name])}" placeholder="${esc(placeholder)}" ${attrs}${errors[name]?' aria-invalid="true" aria-describedby="error-'+name+'"':''}>${errors[name]?`<p class="form-error" id="error-${name}">${errors[name]}</p>`:''}</div>`;}
function editHTML(){const once=editContext.mode==='once';return `<form id="course-form" class="view" novalidate>${Object.keys(errors).length?'<div class="error-summary" role="alert">请检查下方标注的字段后再保存。</div>':''}${once?`<p class="notice">只调整 ${fmtDate(editContext.originalDate)} 这一次课程，其他日期保持不变。</p>`:''}${field('课程名称','name','text','例如：高等数学',once?'readonly':'maxlength="80"')}${once?field('调整到哪一天','targetDate','date','',`min="${TERM_START}" max="${TERM_END}"`):`<div class="form-field"><label for="weekday">星期</label><select id="weekday" name="weekday">${DAYS.map((d,i)=>`<option value="${i+1}" ${+draft.weekday===i+1?'selected':''}>${d}</option>`).join('')}</select></div>`}<span class="form-label">上课时间</span><div class="mode-row">${[['period','按节次'],['custom','自定义时间']].map(([v,l])=>`<button type="button" data-action="time-mode" data-value="${v}" class="${draft.timeMode===v?'active':''}" aria-pressed="${draft.timeMode===v}">${l}</button>`).join('')}</div>${draft.timeMode==='period'?`${field('上课节次','periodText','text','例如：1,2 或 1-2,5')}<p class="field-hint" style="margin-top:-5px;margin-bottom:16px">1–2节 08:30–10:00；3–4节 10:20–11:50<br>非连续节次将分段显示。</p>`:`<div class="form-row">${field('开始时间','start','time')}${field('结束时间','end','time')}</div>`}${field('上课地点','location','text','未确定可以留空','maxlength="80"')}${field('授课教师','teacher','text','未确定可以留空','maxlength="80"')}${!once?`<span class="form-label">教学周次</span><div class="mode-row">${[['all','每周'],['odd','单周'],['even','双周']].map(([v,l])=>`<button type="button" data-action="week-mode" data-value="${v}" class="${draft.weekFilter===v?'active':''}" aria-pressed="${draft.weekFilter===v}">${l}</button>`).join('')}</div>${field('周次范围／自定义周次','weekText','text','例如：1-18 或 5-6,12,17')}<p class="field-hint" style="margin-top:-5px;margin-bottom:16px">本学期共 19 周，可填写非连续周次。</p>`:''}<div class="form-field"><span class="form-label">课程颜色</span><div class="swatches">${COLORS.map((c,i)=>`<button type="button" class="swatch ${draft.color===c?'selected':''}" data-action="color" data-value="${c}" style="--course-bg:var(--${c})" aria-label="${COLOR_NAMES[i]}" aria-pressed="${draft.color===c}"><span></span></button>`).join('')}</div></div><div class="action-area"><button class="primary-btn" type="submit">${icon('check')} ${once?'保存本次调整':'保存课程'}</button></div></form>`;}
function profileHTML(){return `<div class="view"><div class="profile">${books}<div><h1>我的校园手账</h1><p>把课程记清楚<br>也给生活留一点空白。</p></div></div><div class="info-list"><div class="info-row">${icon('book')}<div><b>学校</b><p>山东女子学院 <span class="muted small">· 示例课表</span></p></div></div><div class="info-row">${icon('calendar')}<div><b>当前学期</b><p>2026–2027 学年第一学期<br><span class="small muted">9月14日开始 · 19个教学周</span></p></div></div></div><h2 class="section-title">手账外观</h2><div class="theme-options">${[['light','浅色','sun'],['dark','深色','moon'],['system','跟随系统','screen']].map(([v,l,i])=>`<button class="theme-choice ${theme===v?'selected':''}" data-action="theme" data-value="${v}" aria-pressed="${theme===v}">${icon(i)}${l}</button>`).join('')}</div><p class="profile-note">这里的课程全部是演示数据。<br>可以自由编辑，刷新后回到初始课表。</p></div>`;}
function readDraft(){const f=$('#course-form');if(!f)return;for(const [k,v] of new FormData(f))draft[k]=v;}
function parseNumbers(s,max){s=String(s).replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65248)).replace(/[，、]/g,',').replace(/[–—～~]/g,'-');if(!/^[\d,\s-]+$/.test(s))throw Error('请填写数字、逗号或范围，例如 1-18。');const vals=new Set();for(const part of s.split(',')){const m=part.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw Error('范围格式有误，请检查逗号和数字。');const a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<a||b>max)throw Error(`请填写 1–${max} 内的有效范围。`);for(let i=a;i<=b;i++)vals.add(i);}if(!vals.size)throw Error('至少选择一项。');return [...vals].sort((a,b)=>a-b);}
function saveCourse(){readDraft();errors={};const once=editContext.mode==='once';if(!draft.name.trim())errors.name='请填写课程名称。';let periods=[],weeks=[];if(draft.timeMode==='period'){try{periods=parseNumbers(draft.periodText,12);}catch(e){errors.periodText=e.message;}}else{if(!Number.isFinite(min(draft.start)))errors.start='请填写有效的开始时间。';if(!Number.isFinite(min(draft.end))||min(draft.end)<=min(draft.start))errors.end='结束时间必须晚于开始时间。';}if(!once){try{weeks=parseNumbers(draft.weekText,19).filter(w=>draft.weekFilter==='all'||w%2===(draft.weekFilter==='odd'?1:0));if(!weeks.length)errors.weekText='这些周次与单双周条件没有交集。';}catch(e){errors.weekText=e.message;}}else if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.targetDate)||draft.targetDate<TERM_START||draft.targetDate>TERM_END)errors.targetDate='请选择本学期内的日期。';if(Object.keys(errors).length){render();requestAnimationFrame(()=>{$('[aria-invalid="true"]')?.focus();});return;}
 const values={name:draft.name.trim(),teacher:draft.teacher.trim(),location:draft.location.trim(),color:draft.color,timeMode:draft.timeMode,periods,start:min(draft.start),end:min(draft.end)};
 if(once){const base=courses.find(c=>c.id===editContext.id);const changes={timeMode:values.timeMode,periods:values.periods,start:values.start,end:values.end};for(const k of ['teacher','location','color'])if(values[k]!==base[k])changes[k]=values[k];exceptions[key(editContext.id,editContext.originalDate)]={action:'move',targetDate:draft.targetDate,changes};selectedDate=draft.targetDate;selectedEvent={id:editContext.id,date:draft.targetDate,originalDate:editContext.originalDate};}
 else{Object.assign(values,{weekday:+draft.weekday,weeks});if(editContext.mode==='new'){const id=crypto.randomUUID();courses.push({id,...values});const d=Array.from({length:7},(_,i)=>addDays(monday(selectedDate),i)).find(d=>dayIndex(d)+1===values.weekday&&weeks.includes(weekOf(d)));selectedDate=d||addDays(TERM_START,(weeks[0]-1)*7+values.weekday-1);selectedEvent={id,date:selectedDate,originalDate:selectedDate};originView='home';}else{Object.assign(courses.find(c=>c.id===editContext.id),values);const d=addDays(TERM_START,(weeks[0]-1)*7+values.weekday-1);if(!eventsFor(selectedEvent.date).some(e=>e.id===editContext.id&&e.originalDate===selectedEvent.originalDate)){selectedDate=d;selectedEvent={id:editContext.id,date:d,originalDate:d};}}}
 dirty=false;navigate('detail');toast(once?'这一次课程已调整':'课程已保存');
}
document.addEventListener('input',e=>{if(e.target.closest('#course-form')){dirty=true;readDraft();}});
document.addEventListener('change',e=>{if(e.target.closest('#course-form')){dirty=true;readDraft();}});
document.addEventListener('submit',e=>{if(e.target.id==='course-form'){e.preventDefault();saveCourse();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='nav'){navigate(b.dataset.view);return;}
 if(a==='day'){selectedDate=b.dataset.date;navigate('home');return;}
 if(a==='new'){beginEdit('new');return;}
 if(a==='detail'){originView=view;selectedEvent={id:b.dataset.id,date:b.dataset.date,originalDate:b.dataset.original};navigate('detail');return;}
 if(a==='back'){goBack();return;}
 if(a==='prev-week'||a==='next-week'){const date=addDays(selectedDate,a==='prev-week'?-7:7);if(date>=TERM_START&&date<=TERM_END){selectedDate=date;render();}return;}
 if(a==='date'){openDialog('选择查看日期',`<input class="dialog-input" id="view-date" aria-label="查看日期" type="date" value="${selectedDate}" min="${TERM_START}" max="${TERM_END}">`,'查看课程',()=>{const d=$('#view-date').value;if(d&&d>=TERM_START&&d<=TERM_END){selectedDate=d;navigate('home');}else{$('#view-date').setCustomValidity('请选择本学期内的日期');$('#view-date').reportValidity();return false;}});return;}
 if(a==='edit-whole'||a==='edit-once'){beginEdit(a==='edit-once'?'once':'whole');return;}
 if(a==='cancel-once'){const ev=eventFromSelection();openDialog('标记本次停课？',`<p>${esc(ev.name)}<br>${fmtDate(ev.date)} · ${timeText(ev)}<br>其他周次不会改变。</p>`,'本次停课',()=>{const k=key(ev.id,ev.originalDate),previous=exceptions[k];exceptions[k]={action:'cancel'};selectedDate=ev.date;navigate(originView);toast('已标记本次停课',()=>{if(previous)exceptions[k]=previous;else delete exceptions[k];render();toast('已恢复课程');});});return;}
 if(a==='theme'){theme=b.dataset.value;applyTheme();render();return;}
 if(['time-mode','week-mode','color'].includes(a)){readDraft();draft[a==='time-mode'?'timeMode':a==='week-mode'?'weekFilter':'color']=b.dataset.value;dirty=true;const y=$('#screen').scrollTop;render();$('#screen').scrollTop=y;return;}
 if(a==='dialog-cancel'){$('#dialog').close();dialogAction=null;return;}
 if(a==='dialog-confirm'){const action=dialogAction;if(action?.()===false)return;$('#dialog').close();dialogAction=null;return;}
 if(a==='undo'){const action=toastUndo;toastUndo=null;action?.();return;}
});
applyTheme();render();
